namespace AzerothCoreManager.Services;

public class LocalizationService
{
    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
    {
        ["en"] = new()
        {
            ["app.title"] = "AzerothCore Manager",
            ["nav.dashboard"] = "Dashboard",
            ["nav.setup"] = "Setup",
            ["nav.server_control"] = "Server Control",
            ["nav.gm_console"] = "GM Console",
            ["nav.module_manager"] = "Module Manager",
            ["nav.database"] = "Database",
            ["nav.accounts"] = "Accounts",
            ["nav.settings"] = "Settings",
            ["tool.config_editor"] = "Config Editor",
            ["tool.backup_manager"] = "Backup Manager",
            ["tool.log_viewer"] = "Log Viewer",
            ["status.auth_online"] = "Authserver: Online",
            ["status.auth_offline"] = "Authserver: Offline",
            ["status.world_online"] = "Worldserver: Online",
            ["status.world_offline"] = "Worldserver: Offline",
            ["status.mysql_online"] = "MySQL: Online",
            ["status.mysql_offline"] = "MySQL: Offline",
            ["status.players"] = "Players: {0}",
            ["wizard.title"] = "Welcome to AzerothCore Manager",
            ["wizard.step_check"] = "Step 1/6: System Check",
            ["wizard.step_install"] = "Step 2/6: Installing Prerequisites",
            ["wizard.step_source"] = "Step 3/6: Source Code",
            ["wizard.step_build"] = "Step 4/6: Build",
            ["wizard.step_deploy"] = "Step 5/6: Deploy & Configure",
            ["wizard.step_data"] = "Step 6/6: Client Data",
            ["wizard.complete"] = "Setup Complete!",
            ["wizard.skip"] = "Skip",
            ["wizard.install_all"] = "Install All",
            ["wizard.install_missing"] = "Install Missing",
            ["common.ok"] = "OK",
            ["common.cancel"] = "Cancel",
            ["common.close"] = "Close",
            ["common.save"] = "Save",
            ["common.refresh"] = "Refresh",
            ["common.start"] = "Start",
            ["common.stop"] = "Stop",
            ["common.restart"] = "Restart",
            ["common.backup"] = "Backup",
            ["common.restore"] = "Restore",
            ["common.help"] = "Help",
            ["error.unexpected"] = "An unexpected error occurred.",
        },
        ["de"] = new()
        {
            ["app.title"] = "AzerothCore Manager",
            ["nav.dashboard"] = "Übersicht",
            ["nav.setup"] = "Einrichtung",
            ["nav.server_control"] = "Server-Steuerung",
            ["nav.gm_console"] = "GM-Konsole",
            ["nav.module_manager"] = "Modul-Verwaltung",
            ["nav.database"] = "Datenbank",
            ["nav.accounts"] = "Accounts",
            ["nav.settings"] = "Einstellungen",
            ["tool.config_editor"] = "Config-Editor",
            ["tool.backup_manager"] = "Backup-Verwaltung",
            ["tool.log_viewer"] = "Log-Anzeige",
            ["status.auth_online"] = "Authserver: Online",
            ["status.auth_offline"] = "Authserver: Offline",
            ["status.world_online"] = "Worldserver: Online",
            ["status.world_offline"] = "Worldserver: Offline",
            ["status.mysql_online"] = "MySQL: Online",
            ["status.mysql_offline"] = "MySQL: Offline",
            ["status.players"] = "Spieler: {0}",
            ["wizard.title"] = "Willkommen beim AzerothCore Manager",
            ["wizard.step_check"] = "Schritt 1/6: System-Prüfung",
            ["wizard.step_install"] = "Schritt 2/6: Installation",
            ["wizard.step_source"] = "Schritt 3/6: Quellcode",
            ["wizard.step_build"] = "Schritt 4/6: Kompilieren",
            ["wizard.step_deploy"] = "Schritt 5/6: Deployment & Konfiguration",
            ["wizard.step_data"] = "Schritt 6/6: Client-Daten",
            ["wizard.complete"] = "Einrichtung abgeschlossen!",
            ["wizard.skip"] = "Überspringen",
            ["wizard.install_all"] = "Alle installieren",
            ["wizard.install_missing"] = "Fehlende installieren",
            ["common.ok"] = "OK",
            ["common.cancel"] = "Abbrechen",
            ["common.close"] = "Schließen",
            ["common.save"] = "Speichern",
            ["common.refresh"] = "Aktualisieren",
            ["common.start"] = "Starten",
            ["common.stop"] = "Stoppen",
            ["common.restart"] = "Neustart",
            ["common.backup"] = "Backup",
            ["common.restore"] = "Wiederherstellen",
            ["common.help"] = "Hilfe",
            ["error.unexpected"] = "Ein unerwarteter Fehler ist aufgetreten.",
        },
        // fr, es, zh, ru — prepared, empty
        ["fr"] = new()
        {
            ["app.title"] = "AzerothCore Manager",
            ["nav.dashboard"] = "Tableau de Bord",
            ["nav.setup"] = "Installation",
            ["nav.server_control"] = "Contrôle Serveur",
            ["nav.gm_console"] = "Console GM",
            ["nav.module_manager"] = "Gestion Modules",
            ["nav.database"] = "Base de Données",
            ["nav.accounts"] = "Comptes",
            ["nav.settings"] = "Paramètres",
            ["tool.config_editor"] = "Éditeur Config",
            ["tool.backup_manager"] = "Gestion Sauvegardes",
            ["tool.log_viewer"] = "Visualiseur Logs",
            ["status.auth_online"] = "Authserver : En ligne",
            ["status.auth_offline"] = "Authserver : Hors ligne",
            ["status.world_online"] = "Worldserver : En ligne",
            ["status.world_offline"] = "Worldserver : Hors ligne",
            ["status.mysql_online"] = "MySQL : En ligne",
            ["status.mysql_offline"] = "MySQL : Hors ligne",
            ["status.players"] = "Joueurs : {0}",
            ["wizard.title"] = "Bienvenue dans AzerothCore Manager",
            ["wizard.step_check"] = "Étape 1/6 : Vérification Système",
            ["wizard.step_install"] = "Étape 2/6 : Installation Prérequis",
            ["wizard.step_source"] = "Étape 3/6 : Code Source",
            ["wizard.step_build"] = "Étape 4/6 : Compilation",
            ["wizard.step_deploy"] = "Étape 5/6 : Déploiement & Configuration",
            ["wizard.step_data"] = "Étape 6/6 : Données Client",
            ["wizard.complete"] = "Installation terminée !",
            ["wizard.skip"] = "Passer",
            ["wizard.install_all"] = "Tout Installer",
            ["wizard.install_missing"] = "Installer Manquants",
            ["common.ok"] = "OK",
            ["common.cancel"] = "Annuler",
            ["common.close"] = "Fermer",
            ["common.save"] = "Enregistrer",
            ["common.refresh"] = "Actualiser",
            ["common.start"] = "Démarrer",
            ["common.stop"] = "Arrêter",
            ["common.restart"] = "Redémarrer",
            ["common.backup"] = "Sauvegarder",
            ["common.restore"] = "Restaurer",
            ["common.help"] = "Aide",
            ["error.unexpected"] = "Une erreur inattendue est survenue.",
        },
        ["es"] = new()
        {
            ["app.title"] = "AzerothCore Manager",
            ["nav.dashboard"] = "Panel",
            ["nav.setup"] = "Instalación",
            ["nav.server_control"] = "Control Servidor",
            ["nav.gm_console"] = "Consola GM",
            ["nav.module_manager"] = "Gestor Módulos",
            ["nav.database"] = "Base de Datos",
            ["nav.accounts"] = "Cuentas",
            ["nav.settings"] = "Ajustes",
            ["tool.config_editor"] = "Editor Config",
            ["tool.backup_manager"] = "Gestor Copias",
            ["tool.log_viewer"] = "Visor Logs",
            ["status.auth_online"] = "Authserver: En línea",
            ["status.auth_offline"] = "Authserver: Desconectado",
            ["status.world_online"] = "Worldserver: En línea",
            ["status.world_offline"] = "Worldserver: Desconectado",
            ["status.mysql_online"] = "MySQL: En línea",
            ["status.mysql_offline"] = "MySQL: Desconectado",
            ["status.players"] = "Jugadores: {0}",
            ["wizard.title"] = "Bienvenido a AzerothCore Manager",
            ["wizard.step_check"] = "Paso 1/6: Verificación Sistema",
            ["wizard.step_install"] = "Paso 2/6: Instalación Requisitos",
            ["wizard.step_source"] = "Paso 3/6: Código Fuente",
            ["wizard.step_build"] = "Paso 4/6: Compilación",
            ["wizard.step_deploy"] = "Paso 5/6: Despliegue & Configuración",
            ["wizard.step_data"] = "Paso 6/6: Datos Cliente",
            ["wizard.complete"] = "¡Instalación completa!",
            ["wizard.skip"] = "Omitir",
            ["wizard.install_all"] = "Instalar Todo",
            ["wizard.install_missing"] = "Instalar Faltantes",
            ["common.ok"] = "OK",
            ["common.cancel"] = "Cancelar",
            ["common.close"] = "Cerrar",
            ["common.save"] = "Guardar",
            ["common.refresh"] = "Actualizar",
            ["common.start"] = "Iniciar",
            ["common.stop"] = "Detener",
            ["common.restart"] = "Reiniciar",
            ["common.backup"] = "Copia",
            ["common.restore"] = "Restaurar",
            ["common.help"] = "Ayuda",
            ["error.unexpected"] = "Ocurrió un error inesperado.",
        },
        ["zh"] = new()
        {
            ["app.title"] = "AzerothCore 管理器",
            ["nav.dashboard"] = "仪表板",
            ["nav.setup"] = "安装",
            ["nav.server_control"] = "服务器控制",
            ["nav.gm_console"] = "GM 控制台",
            ["nav.module_manager"] = "模块管理",
            ["nav.database"] = "数据库",
            ["nav.accounts"] = "账户",
            ["nav.settings"] = "设置",
            ["tool.config_editor"] = "配置编辑器",
            ["tool.backup_manager"] = "备份管理",
            ["tool.log_viewer"] = "日志查看器",
            ["status.auth_online"] = "认证服务器：在线",
            ["status.auth_offline"] = "认证服务器：离线",
            ["status.world_online"] = "世界服务器：在线",
            ["status.world_offline"] = "世界服务器：离线",
            ["status.mysql_online"] = "MySQL：在线",
            ["status.mysql_offline"] = "MySQL：离线",
            ["status.players"] = "玩家：{0}",
            ["wizard.title"] = "欢迎使用 AzerothCore 管理器",
            ["wizard.step_check"] = "步骤 1/6：系统检查",
            ["wizard.step_install"] = "步骤 2/6：安装依赖",
            ["wizard.step_source"] = "步骤 3/6：源代码",
            ["wizard.step_build"] = "步骤 4/6：编译",
            ["wizard.step_deploy"] = "步骤 5/6：部署与配置",
            ["wizard.step_data"] = "步骤 6/6：客户端数据",
            ["wizard.complete"] = "安装完成！",
            ["wizard.skip"] = "跳过",
            ["wizard.install_all"] = "全部安装",
            ["wizard.install_missing"] = "安装缺失项",
            ["common.ok"] = "确定",
            ["common.cancel"] = "取消",
            ["common.close"] = "关闭",
            ["common.save"] = "保存",
            ["common.refresh"] = "刷新",
            ["common.start"] = "启动",
            ["common.stop"] = "停止",
            ["common.restart"] = "重启",
            ["common.backup"] = "备份",
            ["common.restore"] = "恢复",
            ["common.help"] = "帮助",
            ["error.unexpected"] = "发生意外错误。",
        },
        ["ru"] = new()
        {
            ["app.title"] = "AzerothCore Manager",
            ["nav.dashboard"] = "Панель",
            ["nav.setup"] = "Установка",
            ["nav.server_control"] = "Управление Сервером",
            ["nav.gm_console"] = "GM Консоль",
            ["nav.module_manager"] = "Менеджер Модулей",
            ["nav.database"] = "База Данных",
            ["nav.accounts"] = "Аккаунты",
            ["nav.settings"] = "Настройки",
            ["tool.config_editor"] = "Редактор Конфигов",
            ["tool.backup_manager"] = "Менеджер Резервных Копий",
            ["tool.log_viewer"] = "Просмотр Логов",
            ["status.auth_online"] = "Authserver: В сети",
            ["status.auth_offline"] = "Authserver: Не в сети",
            ["status.world_online"] = "Worldserver: В сети",
            ["status.world_offline"] = "Worldserver: Не в сети",
            ["status.mysql_online"] = "MySQL: В сети",
            ["status.mysql_offline"] = "MySQL: Не в сети",
            ["status.players"] = "Игроки: {0}",
            ["wizard.title"] = "Добро пожаловать в AzerothCore Manager",
            ["wizard.step_check"] = "Шаг 1/6: Проверка Системы",
            ["wizard.step_install"] = "Шаг 2/6: Установка Зависимостей",
            ["wizard.step_source"] = "Шаг 3/6: Исходный Код",
            ["wizard.step_build"] = "Шаг 4/6: Компиляция",
            ["wizard.step_deploy"] = "Шаг 5/6: Развертывание и Настройка",
            ["wizard.step_data"] = "Шаг 6/6: Данные Клиента",
            ["wizard.complete"] = "Установка завершена!",
            ["wizard.skip"] = "Пропустить",
            ["wizard.install_all"] = "Установить Всё",
            ["wizard.install_missing"] = "Установить Отсутствующие",
            ["common.ok"] = "ОК",
            ["common.cancel"] = "Отмена",
            ["common.close"] = "Закрыть",
            ["common.save"] = "Сохранить",
            ["common.refresh"] = "Обновить",
            ["common.start"] = "Запустить",
            ["common.stop"] = "Остановить",
            ["common.restart"] = "Перезапустить",
            ["common.backup"] = "Резервная Копия",
            ["common.restore"] = "Восстановить",
            ["common.help"] = "Помощь",
            ["error.unexpected"] = "Произошла непредвиденная ошибка.",
        },
    };

    private string _currentLang = "en";

    public string CurrentLanguage => _currentLang;

    public IReadOnlyList<string> AvailableLanguages => Strings.Keys.ToList();

    public string T(string key)
    {
        if (Strings.TryGetValue(_currentLang, out var table) && table.TryGetValue(key, out var value))
            return value;
        // Fallback to English
        if (_currentLang != "en" && Strings.TryGetValue("en", out var enTable) && enTable.TryGetValue(key, out var enValue))
            return enValue;
        return key;
    }

    public string T(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }

    public void SetLanguage(string lang)
    {
        if (Strings.ContainsKey(lang))
            _currentLang = lang;
    }
}
